### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by rahulbf3569** [Merck/psm3mkv#11]
Getting an error while installing "psm3mkv" package in R studio.
Please fine below I shared you the error.

── R CMD build ──────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\DELL\AppData\Local\Temp\RtmpgRosN3\remotes1ca844e12376\Merck-psm3mkv-45a0464/DESCRIPTION' ... 
─  preparing 'psm3mkv':
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (2m 13.3s)
   --- re-building 'background-mortality.Rmd' using rmarkdown
   
   Quitting from lines 128-132 [packages] (background-mortality.Rmd)
   Error: processing vignette 'background-mortality.Rmd' failed with diagnostics:
   there is no package called 'HMDHFDplus'
   --- failed re-building 'background-mortality.Rmd'
   
   --- re-building 'example.Rmd' using rmarkdown
   --- finished re-building 'example.Rmd'
   
   SUMMARY: processing the following file failed:
     'background-mortality.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'psm3mkv' from GitHub:
  ! System command 'Rcmd.exe' failed

**Comment by dom-muston** [comment]
Thanks for trying out the package. I'm sorry you are seeing an error. It may take me a little while to update the package but I n the mean time, I'd suggest to either:
- install the "HMDHFDplus" package used in the vignette before installing psm3mkv; or
- install psm3mkv package with the build vignettes flag set to false.
