### ISSUE TITLE
Package installation instructions

### ISSUE THREAD

**Issue by nialldavison** [Merck/psm3mkv#13]
Thank you for developing this package. We have enjoyed looking through it and are interested in its future development!
We have some suggestions regarding the package’s recommended installation approach, as of `psm3mkv` version *0.2.0.9000*.

Currently the README and vignettes suggest using `remotes::install_github` with `build_vignettes = TRUE`, like so:

```{r}
# Install version 0.2 from Github as follows, with the vignette
remotes::install_github("Merck/psm3mkv",
    ref="v0.2",
    build_vignettes=TRUE)
```

Within the vignettes, the following code is also added (*the vector called "packages" varies*):

```{r}
# First specify the packages of interest
packages = c("psm3mkv", "dplyr", "flexsurv", "HMDHFDplus", "remotes")

# Now load or install & load all
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)
```

For me and another colleague (@BKievit1), both using relatively powerful machines, this approach took over 5 minutes to install the package. Errors related to missing packages (namely `HMDHFDplus`) were not addressed by the `package.check` approach implemented above.

Our suggestions are:

* Confirm whether vignettes should really include installation commands for the package, and whether use of `build_vignettes = TRUE` within the vignettes themselves may result in **circular logic**, which is extending the time to installation. Typically, a vignette would just attach the main package via `library()`, with any installation code stored within code chunks set to `eval = FALSE`.
* Confirm whether users really need to build vignettes by default, given you have a functioning github.io site (https://merck.github.io/psm3mkv) where the users can access the vignettes already.
* If the default installation approach is to build vignettes that rely on the user having installed other packages, consider moving these packages to the psm3mkv imports, to avoid off-putting errors. If you want to keep a low number of dependencies, instead consider a dedicated package manager such as `pacman` (https://github.com/trinker/pacman) and using `pacman::p_load` within the vignette to install, load, and update a list of desired packages. For example:
```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(packages)
```
* Use <- for assignment of the `packages` vector, instead of ‘=’, per R standard practice.
* Consider using `pak` (https://github.com/r-lib/pak) instead of `remotes` as the default installation recommendation for `psm3mkv`. `pak` helps to avoid headaches like corrupted package installations, incompatible dependency versions, or problems with installing packages that are already loaded. In the 2nd edition of ‘R Packages’ by Wickham and Bryan (https://r-pkgs.org/structure.html#sec-installed-package), it is predicted that pak *“will soon become our official recommendation for how to install packages”*, and that *“it is likely that remotes will essentially become superseded, in favor of pak, but we’re not quite there yet"*.

**Comment by dom-muston** [comment]
Thanks again for your review. I'm reworking vignette 2 and appreciate the feedback on ease of use of vignettes and installation - or rather unease.

**Comment by dom-muston** [comment]
Thank you again! I have aimed to address via Pulls 21 & 22
