### ISSUE TITLE
Release psm3mkv 0.3.0

### ISSUE THREAD

**Issue by nanxstats** [Merck/psm3mkv#28]
First release

- [x] Proof read `Title:` and `Description:` and ensure they are informative
- [x] Check that all exported functions have `@returns` and `@examples`
- [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
- [x] Review [extrachecks](https://github.com/DavisVaughan/extrachecks)
- [x] `usethis::use_cran_comments()` (optional)

Prepare for release

- [x] Check current CRAN check results
- [x] Check licensing of included files
- [x] Review pkgdown reference index for, e.g., missing topics
- [x] Bump version
- [x] Update `cran-comments.md` (optional)
- [x] Update NEWS.md
- [x] Review pkgdown website
- [x] `urlchecker::url_check()`
- [x] Check with local machine
- [x] Check with GitHub Actions
- [x] Check with win-builder

Submit to CRAN

- [x] Draft GitHub release
- [x] Submit to CRAN via web form
- [x] Approve emails

Wait for CRAN

- [ ] Accepted :tada:

**Comment by dom-muston** [comment]
Now submitted to CRAN!

The devtools command from the [R packages book](https://devtools.r-lib.org/reference/submit_cran.html) made this pretty easy.

`devtools::submit_cran()`

Let's see how many errors, warnings, notes etc come up...

**Comment by nanxstats** [comment]
Nice! There are two dashboards for tracking the submission status:

https://r-hub.github.io/cransays/articles/dashboard.html
https://nx10.github.io/cransubs/

**Comment by dom-muston** [comment]
Thanks Nan, you have a very nice tracker there.

**Comment by nanxstats** [comment]
I see 0.3.0 was rejected and 0.3.1 has been submitted, so I'm closing this for now. For each CRAN release, you can create a new release checklist by copying this.
